In [1]:
import sys
import numpy as np
import matplotlib
print('python',sys.version)
print('Numpy',np.version.version)
print('Matplotlib',matplotlib.__version__)

python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:38:29) [Clang 13.0.1 ]
Numpy 1.23.2
Matplotlib 3.6.2


For 1 Neuron with 3 inputs

In [2]:
inputs=[1,2,3]
weights=[4,5,6]
bias=3
output=inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+bias
print(output)


35


For 3 Neuron with 4 inputs

In [3]:
inputs=[1,2,3,1.5]
weights1=[0.2,-0.1,0.4,0.8]
weights2=[0.5,-0.6,-0.7,0.8]
weights3=[-0.26,-0.27,0.17,0.87]
bias1=3
bias2=2
bias3=0.5
output=[inputs[0]*weights1[0]+inputs[1]*weights1[1]+inputs[2]*weights3[2]+bias1,
        inputs[0]*weights2[0]+inputs[1]*weights2[1]+inputs[2]*weights3[2]+bias2,
        inputs[0]*weights3[0]+inputs[1]*weights3[1]+inputs[2]*weights3[2]+bias3]
print(output)


[3.51, 1.81, 0.20999999999999996]


We can also write the above code as :


In [4]:
input=[1,2,3,1.5]
weights=[[0.2,-0.1,0.4,0.8],[0.5,-0.6,-0.7,0.8],[-0.26,-0.27,0.17,0.87]]
bias=[3,2,0.5]
output=np.dot(weights,input)+bias #weight should be always first
print(output)

[5.4   0.4   1.515]


Trying dot product 

In [5]:
input=[[1,2,3,4],[2,3,4,1],[-2,-1,4,2]]
weights=[[-4,2,4,3],[-2,-4,-5,2],[4,2,3,1]]
bias=[3,2,0.5]
output=np.dot(input,weights)+bias
print(output) #here we neeed to transpose the weights values for making 3*4 and 4*3 martix

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

Making transpose of weights

In [6]:
output=np.dot(input,np.array(weights).T)+bias
print(output)

[[ 27.  -15.   21.5]
 [ 20.  -32.   27.5]
 [ 31.   -6.    4.5]]


Working on with two layers transpose

In [7]:
input=[[1,2,3,4],[2,3,4,1],[-2,-1,4,2]] #4*4 matrix
weights=[[-4,2,4,3],[-2,-4,-5,2],[4,2,3,1]] #4*4 matrix
bias=[3,2,0.5]
input1=[[2,2,-2],[2,3,2],[-2,-1,4]] #3*3 matrix
weights1=[[-3,2,4],[-2,-4,2],[4,2,3]] #3*3 matrix
bias1=[3,-2,1]
output=np.dot(input,np.array(weights).T)+bias
output1=np.dot(output,np.array(weights1).T)+bias1
print(output1)

[[-22.   47.  143.5]
 [-11.  141.   99.5]
 [-84.  -31.  126.5]]


Forward Method

In [8]:
np.random.seed(0)

X = [[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]


class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

layer1 = Layer_Dense(4,5)
layer2 = Layer_Dense(5,2)

layer1.forward(X)
#print(layer1.output)
layer2.forward(layer1.output)
print(layer2.output)

[[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]


Hidden layer Activation Function

In [9]:
inputs=[-2,1,3,2,-4.2,9,-5]
output=[]
for i in inputs:
    if i>0:
        print(output.append(i))
    elif i<=0:
        print(output.append(0))
print(output)

None
None
None
None
None
None
None
[0, 1, 3, 2, 0, 9, 0]


In [10]:
import numpy as np 
import nnfs
from nnfs import spiral_data
X, y = spiral_data(100, 3)   


class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases


class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)


layer1 = Layer_Dense(2,5)
activation1 = Activation_ReLU()

layer1.forward(X)

#print(layer1.output)
activation1.forward(layer1.output)
print(activation1.output)

ModuleNotFoundError: No module named 'nnfs'

### Softmax activation

Exponential value

In [11]:
import math
layer_output=[2.1,4.5,6.1]
E=math.e
exp_values=[]
for exp in layer_output:
    exp_values.append(E**exp)
print(exp_values)

[8.16616991256765, 90.0171313005218, 445.85777008251665]


Normalization

In [12]:
norm_base=sum(exp_values)
norm_values=[]
for value in exp_values:
    norm_values.append(value/norm_base)
print(norm_values)
print(sum(norm_values))

[0.015010208499737587, 0.16546017580281316, 0.8195296156974492]
1.0


using numpy for exponential and normalization 

In [13]:
exp_values=np.exp(layer_output)
norm_values=exp_values/np.sum(exp_values)
print(exp_values)
print(sum(norm_values))

[  8.16616991  90.0171313  445.85777008]
1.0


Adding rows and column of 3*3 matrix

In [14]:
layer_output=[[2.1,4.5,6.1],
             [3.5,5.2,2.2],
             [1.4,2.6,4.6]]
exp_values=np.exp(layer_output)
print(np.sum(layer_output,axis=1,keepdims=False)) #axis=1 is for the row value
print(np.sum(layer_output,axis=0,keepdims=False)) #axis=0 is for the column value and keepdims=false keep dimension horizontal

[12.7 10.9  8.6]
[ 7.  12.3 12.9]


### Loss with categorical cross-entropy

In [15]:
#solving for x
#e**x=b

import math
import numpy as np
x=5.2
print(np.log(x))
print(math.e**1.64) #e value is 1.64


1.6486586255873816
5.15516951223468


calculating loss function

In [16]:
softmax_output=[4.2,5.1,6.3] #all inputs should be postive otherwise there will be math domain error
target_output=[3.2,5.3,1.2]

loss= -(math.log(softmax_output[0])*target_output[0]+
        math.log(softmax_output[1])*target_output[1]+
        math.log(softmax_output[2])*target_output[2])
print(loss)

-15.435904901573302
